from app.services.classifier import DocumentClassifier

invoice_examples = [
    "Invoice dated March 10 for consulting services worth $1,200.",
    "Please find attached the invoice for your recent order of supplies.",
    "This invoice is generated for the software license renewal.",
    "Payment is due within 15 days from the invoice date.",
    "Invoice #45678 includes charges for web development.",
    "Billing summary: Total due $875 for January maintenance.",
    "Your invoice for quarterly audit services is attached.",
    "Kindly process the invoice for shipment and handling fees.",
    "Final invoice for mobile app development project.",
    "Enclosed invoice covers training services conducted in April.",
    "Enclosed invoice details Invoice dated March 10 for consulting services worth $1,200.",
    "Enclosed invoice details Please find attached the invoice for your recent order of supplies.",
    "You have been invoiced for This invoice is generated for the software license renewal.",
    "Enclosed invoice details Payment is due within 15 days from the invoice date.",
    "Payment invoice issued regarding Invoice #45678 includes charges for web development.",
    "Payment invoice issued regarding Billing summary: Total due $875 for January maintenance.",
    "You have been invoiced for Your invoice for quarterly audit services is attached.",
    "This document serves as an invoice for Kindly process the invoice for shipment and handling fees.",
    "Invoice for Final invoice for mobile app development project.",
    "Invoice for Enclosed invoice covers training services conducted in April.",
    "Enclosed invoice details Invoice dated March 10 for consulting services worth $1,200.",
    "Payment invoice issued regarding Please find attached the invoice for your recent order of supplies.",
    "Payment invoice issued regarding This invoice is generated for the software license renewal.",
    "Enclosed invoice details Payment is due within 15 days from the invoice date.",
    "This document serves as an invoice for Invoice #45678 includes charges for web development.",
    "You have been invoiced for Billing summary: Total due $875 for January maintenance.",
    "This document serves as an invoice for Your invoice for quarterly audit services is attached.",
    "You have been invoiced for Kindly process the invoice for shipment and handling fees.",
    "Enclosed invoice details Final invoice for mobile app development project.",
    "Invoice for Enclosed invoice covers training services conducted in April.",
    "You have been invoiced for Invoice dated March 10 for consulting services worth $1,200.",
    "You have been invoiced for Please find attached the invoice for your recent order of supplies.",
    "This document serves as an invoice for This invoice is generated for the software license renewal.",
    "Payment invoice issued regarding Payment is due within 15 days from the invoice date.",
    "You have been invoiced for Invoice #45678 includes charges for web development.",
    "Enclosed invoice details Billing summary: Total due $875 for January maintenance.",
    "Payment invoice issued regarding Your invoice for quarterly audit services is attached.",
    "Payment invoice issued regarding Kindly process the invoice for shipment and handling fees.",
    "Enclosed invoice details Final invoice for mobile app development project.",
    "Payment invoice issued regarding Enclosed invoice covers training services conducted in April.",
    "You have been invoiced for Invoice dated March 10 for consulting services worth $1,200.",
    "This document serves as an invoice for Please find attached the invoice for your recent order of supplies.",
    "Enclosed invoice details This invoice is generated for the software license renewal.",
    "This document serves as an invoice for Payment is due within 15 days from the invoice date.",
    "Invoice for Invoice #45678 includes charges for web development.",
    "You have been invoiced for Billing summary: Total due $875 for January maintenance.",
    "Invoice for Your invoice for quarterly audit services is attached.",
    "Enclosed invoice details Kindly process the invoice for shipment and handling fees.",
    "You have been invoiced for Final invoice for mobile app development project.",
    "Invoice for Enclosed invoice covers training services conducted in April.",
]

contract_examples = [
    "This agreement is made and entered into by both parties on June 5.",
    "The contract outlines the terms of the employment offer.",
    "This legally binding contract is effective from July 1.",
    "Both organizations agree to the conditions set forth in this contract.",
    "Termination clauses are outlined in section 4 of the contract.",
    "The signed contract governs the leasing of equipment.",
    "The contractor agrees to deliver services as per this agreement.",
    "This document represents a mutual contract between client and vendor.",
    "Confidentiality terms are part of this contract.",
    "The partnership contract lasts for a period of two years.",
    "Agreement terms cover This agreement is made and entered into by both parties on June 5.",
    "The contract outlines The contract outlines the terms of the employment offer.",
    "Agreement terms cover This legally binding contract is effective from July 1.",
    "Binding contract applies to Both organizations agree to the conditions set forth in this contract.",
    "This legal contract confirms Termination clauses are outlined in section 4 of the contract.",
    "Agreement terms cover The signed contract governs the leasing of equipment.",
    "Agreement terms cover The contractor agrees to deliver services as per this agreement.",
    "Binding contract applies to This document represents a mutual contract between client and vendor.",
    "Binding contract applies to Confidentiality terms are part of this contract.",
    "This legal contract confirms The partnership contract lasts for a period of two years.",
    "The contract outlines This agreement is made and entered into by both parties on June 5.",
    "This legal contract confirms The contract outlines the terms of the employment offer.",
    "Binding contract applies to This legally binding contract is effective from July 1.",
    "Binding contract applies to Both organizations agree to the conditions set forth in this contract.",
    "The contract outlines Termination clauses are outlined in section 4 of the contract.",
    "The contract outlines The signed contract governs the leasing of equipment.",
    "Binding contract applies to The contractor agrees to deliver services as per this agreement.",
    "The contract outlines This document represents a mutual contract between client and vendor.",
    "Agreement terms cover Confidentiality terms are part of this contract.",
    "The contract outlines The partnership contract lasts for a period of two years.",
    "This legal contract confirms This agreement is made and entered into by both parties on June 5.",
    "Agreement terms cover The contract outlines the terms of the employment offer.",
    "The contract outlines This legally binding contract is effective from July 1.",
    "The contract outlines Both organizations agree to the conditions set forth in this contract.",
    "This legal contract confirms Termination clauses are outlined in section 4 of the contract.",
    "Contract signed regarding The signed contract governs the leasing of equipment.",
    "Contract signed regarding The contractor agrees to deliver services as per this agreement.",
    "Agreement terms cover This document represents a mutual contract between client and vendor.",
    "The contract outlines Confidentiality terms are part of this contract.",
    "Contract signed regarding The partnership contract lasts for a period of two years.",
    "This legal contract confirms This agreement is made and entered into by both parties on June 5.",
    "This legal contract confirms The contract outlines the terms of the employment offer.",
    "Contract signed regarding This legally binding contract is effective from July 1.",
    "The contract outlines Both organizations agree to the conditions set forth in this contract.",
    "The contract outlines Termination clauses are outlined in section 4 of the contract.",
    "The contract outlines The signed contract governs the leasing of equipment.",
    "Contract signed regarding The contractor agrees to deliver services as per this agreement.",
    "Binding contract applies to This document represents a mutual contract between client and vendor.",
    "The contract outlines Confidentiality terms are part of this contract.",
    "Agreement terms cover The partnership contract lasts for a period of two years.",
]

resume_examples = [
    "John Doe's resume includes experience in Python, Java, and machine learning.",
    "Experienced software engineer with 5 years in backend development.",
    "Certified project manager with a strong record in Agile delivery.",
    "Resume highlights leadership, communication, and time management skills.",
    "Seeking a position as a data analyst with strong SQL and Excel skills.",
    "Graduate student with a degree in Computer Science and internship experience.",
    "Senior marketing executive with a focus on brand strategy and digital media.",
    "Jane Smith's resume reflects strong expertise in cloud computing and DevOps.",
    "Experience includes Salesforce CRM, HubSpot, and marketing automation tools.",
    "Familiar with HTML, CSS, and JavaScript for front-end web development.",
    "Job application highlights John Doe's resume includes experience in Python, Java, and machine learning.",
    "Work history shows expertise in Experienced software engineer with 5 years in backend development.",
    "Professional summary includes Certified project manager with a strong record in Agile delivery.",
    "Resume outlines experience in Resume highlights leadership, communication, and time management skills.",
    "Work history shows expertise in Seeking a position as a data analyst with strong SQL and Excel skills.",
    "Professional summary includes Graduate student with a degree in Computer Science and internship experience.",
    "Resume outlines experience in Senior marketing executive with a focus on brand strategy and digital media.",
    "Job application highlights Jane Smith's resume reflects strong expertise in cloud computing and DevOps.",
    "Work history shows expertise in Experience includes Salesforce CRM, HubSpot, and marketing automation tools.",
    "Resume outlines experience in Familiar with HTML, CSS, and JavaScript for front-end web development.",
    "Job application highlights John Doe's resume includes experience in Python, Java, and machine learning.",
    "Work history shows expertise in Experienced software engineer with 5 years in backend development.",
    "Job application highlights Certified project manager with a strong record in Agile delivery.",
    "Candidate has skills in Resume highlights leadership, communication, and time management skills.",
    "Work history shows expertise in Seeking a position as a data analyst with strong SQL and Excel skills.",
    "Resume outlines experience in Graduate student with a degree in Computer Science and internship experience.",
    "Job application highlights Senior marketing executive with a focus on brand strategy and digital media.",
    "Candidate has skills in Jane Smith's resume reflects strong expertise in cloud computing and DevOps.",
    "Work history shows expertise in Experience includes Salesforce CRM, HubSpot, and marketing automation tools.",
    "Work history shows expertise in Familiar with HTML, CSS, and JavaScript for front-end web development.",
    "Resume outlines experience in John Doe's resume includes experience in Python, Java, and machine learning.",
    "Work history shows expertise in Experienced software engineer with 5 years in backend development.",
    "Professional summary includes Certified project manager with a strong record in Agile delivery.",
    "Work history shows expertise in Resume highlights leadership, communication, and time management skills.",
    "Candidate has skills in Seeking a position as a data analyst with strong SQL and Excel skills.",
    "Candidate has skills in Graduate student with a degree in Computer Science and internship experience.",
    "Candidate has skills in Senior marketing executive with a focus on brand strategy and digital media.",
    "Professional summary includes Jane Smith's resume reflects strong expertise in cloud computing and DevOps.",
    "Work history shows expertise in Experience includes Salesforce CRM, HubSpot, and marketing automation tools.",
    "Professional summary includes Familiar with HTML, CSS, and JavaScript for front-end web development.",
    "Resume outlines experience in John Doe's resume includes experience in Python, Java, and machine learning.",
    "Work history shows expertise in Experienced software engineer with 5 years in backend development.",
    "Candidate has skills in Certified project manager with a strong record in Agile delivery.",
    "Work history shows expertise in Resume highlights leadership, communication, and time management skills.",
    "Resume outlines experience in Seeking a position as a data analyst with strong SQL and Excel skills.",
    "Candidate has skills in Graduate student with a degree in Computer Science and internship experience.",
    "Work history shows expertise in Senior marketing executive with a focus on brand strategy and digital media.",
    "Resume outlines experience in Jane Smith's resume reflects strong expertise in cloud computing and DevOps.",
    "Work history shows expertise in Experience includes Salesforce CRM, HubSpot, and marketing automation tools.",
    "Job application highlights Familiar with HTML, CSS, and JavaScript for front-end web development.",
]

legal_doc_examples = [
    "The court hereby rules in favor of the plaintiff.",
    "This legal document affirms the transfer of ownership.",
    "The defendant has violated section 8 of the labor law.",
    "This is a notarized copy of the legal proceedings.",
    "The document outlines terms of the legal settlement.",
    "Witness statements are included in the legal case file.",
    "Summons issued for the hearing on October 5.",
    "The case is dismissed due to lack of evidence.",
    "Legal counsel is advised to file a counter-motion.",
    "The judge’s verdict was recorded on page 12.",
    "Court order issued for The court hereby rules in favor of the plaintiff.",
    "Legal document confirms This legal document affirms the transfer of ownership.",
    "Summons and ruling related to The defendant has violated section 8 of the labor law.",
    "Court order issued for This is a notarized copy of the legal proceedings.",
    "This document addresses The document outlines terms of the legal settlement.",
    "This document addresses Witness statements are included in the legal case file.",
    "This document addresses Summons issued for the hearing on October 5.",
    "Legal document confirms The case is dismissed due to lack of evidence.",
    "Lawyer submitted a motion for Legal counsel is advised to file a counter-motion.",
    "This document addresses The judge’s verdict was recorded on page 12.",
    "Lawyer submitted a motion for The court hereby rules in favor of the plaintiff.",
    "Court order issued for This legal document affirms the transfer of ownership.",
    "Court order issued for The defendant has violated section 8 of the labor law.",
    "Legal document confirms This is a notarized copy of the legal proceedings.",
    "This document addresses The document outlines terms of the legal settlement.",
    "Lawyer submitted a motion for Witness statements are included in the legal case file.",
    "Legal document confirms Summons issued for the hearing on October 5.",
    "This document addresses The case is dismissed due to lack of evidence.",
    "Court order issued for Legal counsel is advised to file a counter-motion.",
    "Lawyer submitted a motion for The judge’s verdict was recorded on page 12.",
    "Legal document confirms The court hereby rules in favor of the plaintiff.",
    "Summons and ruling related to This legal document affirms the transfer of ownership.",
    "Lawyer submitted a motion for The defendant has violated section 8 of the labor law.",
    "This document addresses This is a notarized copy of the legal proceedings.",
    "Lawyer submitted a motion for The document outlines terms of the legal settlement.",
    "Court order issued for Witness statements are included in the legal case file.",
    "Court order issued for Summons issued for the hearing on October 5.",
    "Summons and ruling related to The case is dismissed due to lack of evidence.",
    "Summons and ruling related to Legal counsel is advised to file a counter-motion.",
    "This document addresses The judge’s verdict was recorded on page 12.",
    "Court order issued for The court hereby rules in favor of the plaintiff.",
    "Legal document confirms This legal document affirms the transfer of ownership.",
    "Court order issued for The defendant has violated section 8 of the labor law.",
    "This document addresses This is a notarized copy of the legal proceedings.",
    "Summons and ruling related to The document outlines terms of the legal settlement.",
    "Lawyer submitted a motion for Witness statements are included in the legal case file.",
    "This document addresses Summons issued for the hearing on October 5.",
    "Court order issued for The case is dismissed due to lack of evidence.",
    "Court order issued for Legal counsel is advised to file a counter-motion.",
    "Summons and ruling related to The judge’s verdict was recorded on page 12.",
]


texts = invoice_examples + contract_examples + resume_examples + legal_doc_examples
labels = (['invoice'] * len(invoice_examples) +
          ['contract'] * len(contract_examples) +
          ['resume'] * len(resume_examples) +
          ['legal_doc'] * len(legal_doc_examples))

classifier = DocumentClassifier()
classifier.train(texts, labels)
